### ISSUE TITLE
NaN

### ISSUE THREAD

**Issue by ttorkar** [wyfsh/YOLO-LISA#1]
Hi Jianming Zhang, Manting Huang, Xiaokang Jin and Xudong Li,

I enjoyed reading your paper and I am impressed with the good work. My issue is this, when I use five anchor boxes, it works perfectly. When I use eight anchor boxes, after 250+ steps I experience NaNs. Have you experienced this? Do you have any understanding about why this could be occurring?

Thanks, 

Trent

**Comment by wyfsh** [comment]
Hi @ttorkar 

This is Yifan. I believe you have mistaken me for the paper writers. You should check the paper again, and email to jmzhang at csust.edu.cn (J.Z.) or huangmt at stu.csust.edu.cn (M.H.). Also you may contact with Joseph Redmon ([YOLO](https://pjreddie.com/darknet/yolo/)'s father) for help.

Good luck!
